{% set name = "symjit" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/symjit-{{ version }}.tar.gz
  sha256: 17a9040b5a40901a53988524b1618b7b99215bd71a6102886c76da294a8557e0

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
  run:
    - numpy
    - python
    - sympy

test:
  files:
    - test.py
  imports:
    - symjit
  commands:
    - pip check
    - python test.py
  requires:
    - pip

about:
  home: https://github.com/siravan/symjit
  license: MIT
  license_file:
    - LICENSE
    # - THIRDPARTY.yml
  summary: |
    Symjit is a lightweight just-in-time (JIT) compiler that directly
    translates sympy expressions into machine code.

extra:
  recipe-maintainers:
    - moorepants
    - shahriariravanian
