{% set name = "symjit" %}
{% set version = "2.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/66/c4/dd6b27286471e4420dd191f1ddbd3ab99c8d1e603b4f6a9c734672f74487/symjit-{{ version }}.tar.gz
  sha256: 5719cfc3465e63eccd59145d0ffa038a128b7f900cf2c19369b2717e98868e19

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
  run:
    - numpy
    - python
    - sympy

test:
  files:
    - test.py
  imports:
    - symjit
  commands:
    - pip check
    - python test.py
  requires:
    - pip

about:
  home: https://github.com/siravan/symjit
  license: MIT
  license_file:
    - LICENSE
    # - THIRDPARTY.yml
  summary: |
    Symjit is a lightweight just-in-time (JIT) compiler that directly
    translates sympy expressions into machine code.

extra:
  recipe-maintainers:
    - moorepants
    - shahriariravanian
