{% set name = "symjit" %}
{% set version = "2.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/53/61/982f8ce15576f030fb979e60fe34067bc9702087ce807356dced6c47487a/symjit-{{ version }}.tar.gz
  sha256: 650cfaf63d57a91f3ab52273cafb233caf172d92ef693f5fc3d6e2fd03d1535b

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
  run:
    - numpy
    - python
    - sympy

test:
  files:
    - test.py
  imports:
    - symjit
  commands:
    - pip check
    - python test.py
  requires:
    - pip

about:
  home: https://github.com/siravan/symjit
  license: MIT
  license_file:
    - LICENSE
    # - THIRDPARTY.yml
  summary: |
    Symjit is a lightweight just-in-time (JIT) compiler that directly
    translates sympy expressions into machine code.

extra:
  recipe-maintainers:
    - moorepants
    - shahriariravanian
